# Supported funding model platforms
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: TheWidlarzGroup
custom:
  - https://sdk.thewidlarzgroup.com/?utm_source=rnv&utm_medium=github-funding&utm_campaign=sponsor-button
