name: Bug report
description: Create a report to help us improve
title: "[BUG]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report! Please do not report issue on 5.2.1 version, this version is not maintained anymore. Only issues on version > V6 will be handled. Please also ensure your issue is reproduced with the last release!

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using? Put the exact version from your package.json
    validations:
      required: true

  - type: dropdown
    id: platforms
    validations:
      required: true
    attributes:
      label: What platforms are you having the problem on?
      multiple: true
      options:
        - iOS
        - Android
        - Windows
        - visionOS
        - Android TV
        - Apple tvOS

  - type: input
    id: system_version
    attributes:
      label: System Version
      description: What version of the system is using device that you are experiencing the issue?
    validations:
      required: true

  - type: dropdown
    id: device
    validations:
      required: true
    attributes:
      label: On what device are you experiencing the issue?
      multiple: true
      options:
        - Real device
        - Simulator
  
  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      description: What architecture are you using?
      options:
        - Old architecture
        - New architecture with interop layer
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  
  - type: input
    id: reproduction-repo
    attributes:
      label: Reproduction
      description: Provide a link to a repository with a reproduction of the bug, this is optional but it will make us to fix the bug faster
      placeholder: Reproduction Repository
      value: "repository link"
    validations:
      required: false

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Tell us how can we reproduce this bug
      placeholder: Reproduction
      value: "Step to reproduce this bug are: "
    validations:
      required: true
