# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!


ENV['RCT_NEW_ARCH_ENABLED'] = '1'
if ENV['RCT_NEW_ARCH_ENABLED'] == '1'
  Pod::UI.puts "New Architecture is ENABLED".green
else
  Pod::UI.puts "New Architecture is DISABLED".red
end

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'VideoExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Xcode 26's Apple Clang 21 is stricter about consteval call sites, which breaks
    # fmt 11.0.2's FMT_STRING(...) usages (https://github.com/fmtlib/fmt/issues/4740,
    # https://github.com/facebook/react-native/issues/55601, #5080). consteval doesn't
    # exist pre-C++20, so building just the fmt pod as C++17 sidesteps the strict check.
    # TODO: Verify and remove after updating RN to version 0.84 or later
    installer.pods_project.targets.each do |target|
      if target.name == 'fmt'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
    end
  end
end
