# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

require_relative 'scripts/patch_fmt_consteval'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Link the Google IMA SDK into react-native-video so this example app exercises
# the real client-side ad insertion path. Must be set before `use_native_modules!`
# evaluates ReactNativeVideo.podspec.
$RNVideoUseGoogleIMA = true


ENV['RCT_NEW_ARCH_ENABLED'] = '1'
if ENV['RCT_NEW_ARCH_ENABLED'] == '1'
  Pod::UI.puts "New Architecture is ENABLED".green
else
  Pod::UI.puts "New Architecture is DISABLED".red
end

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'VideoExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Pods/ is gitignored, so this has to re-run on every `pod install`.
    RNVideoFmtConstevalPatch.apply!(installer)
  end
end
