require_relative 'node_modules/react-native-test-app/test_app'

use_flipper!

workspace 'VideoCaching.xcworkspace'

use_test_app! do |target|
    target.app do
        pod 'DVAssetLoaderDelegate', :modular_headers => true
        pod 'SPTPersistentCache', :modular_headers => true
        pod 'react-native-video/VideoCaching', :path => '../../react-native-video.podspec'
    end
end
