name: Build iOS

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-ios.yml'
      - 'packages/react-native-video/ios/**'
      - '*.podspec'
      - 'examples/bare/ios/**'
  pull_request:
    paths:
      - '.github/workflows/build-ios.yml'
      - 'packages/react-native-video/ios/**'
      - '*.podspec'
      - 'examples/bare/ios/**'

jobs:
  build: 
    name: Build iOS Example App
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies (with bun)
        run: bun install

      - name: Restore buildcache
        uses: mikehardy/buildcache-action@v2
        continue-on-error: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
          working-directory: examples/bare/ios

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Restore Pods cache
        uses: actions/cache@v4
        with:
          path: examples/bare/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock', '**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Generate Native Project
        working-directory: examples/bare/ios
        run: pod install

      - name: Install Pods
        working-directory: examples/bare/ios
        run: pod install

      - name: Build App
        working-directory: examples/bare/ios
        run: "set -o pipefail && xcodebuild \
          -derivedDataPath build -UseModernBuildSystem=YES \
          -workspace BareExample.xcworkspace \
          -scheme BareExample \
          -sdk iphonesimulator \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 14' \
          build \
          CODE_SIGNING_ALLOWED=NO | xcpretty"
  
  build-with-ads:
    name: Build iOS Example App with Ads
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies (with bun)
        run: bun install

      - name: Restore buildcache
        uses: mikehardy/buildcache-action@v2
        continue-on-error: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
          working-directory: examples/bare/ios

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Restore Pods cache
        uses: actions/cache@v4
        with:
          path: examples/bare/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock', '**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Generate Native Project
        working-directory: examples/bare/ios
        run: export RNV_SAMPLE_ENABLE_ADS=true && pod install

      - name: Install Pods
        working-directory: examples/bare/ios
        run: export RNV_SAMPLE_ENABLE_ADS=true && pod install

      - name: Build App
        working-directory: examples/bare/ios
        run: "set -o pipefail && xcodebuild \
          -derivedDataPath build -UseModernBuildSystem=YES \
          -workspace BareExample.xcworkspace \
          -scheme BareExample \
          -sdk iphonesimulator \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 14' \
          build \
          CODE_SIGNING_ALLOWED=NO | xcpretty"
  
  build-with-caching: 
    name: Build iOS Example App with Caching
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies (with bun)
        run: bun install

      - name: Restore buildcache
        uses: mikehardy/buildcache-action@v2
        continue-on-error: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
          working-directory: examples/bare/ios

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Restore Pods cache
        uses: actions/cache@v4
        with:
          path: examples/bare/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock', '**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Generate Native Project
        working-directory: examples/bare/ios
        run: export RNV_SAMPLE_VIDEO_CACHING=true && pod install

      - name: Install Pods
        working-directory: examples/bare/ios
        run: export RNV_SAMPLE_VIDEO_CACHING=true && pod install

      - name: Build App
        working-directory: examples/bare/ios
        run: "set -o pipefail && xcodebuild \
          -derivedDataPath build -UseModernBuildSystem=YES \
          -workspace BareExample.xcworkspace \
          -scheme BareExample \
          -sdk iphonesimulator \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 14' \
          build \
          CODE_SIGNING_ALLOWED=NO | xcpretty"