name: Publish Release on GitHub

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://npm.pkg.github.com'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install

    - name: Prepare release
      run: bun run scripts/release.js --no-release

    - name: Publish release
      run: cd packages/react-native-video && npm publish --tag dev
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}