
name: Test Docs build
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/test-build-docs.yml'
      - 'docs/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-bun
        with:
          working-directory: ./docs

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            docs/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}
            ${{ runner.os }}-nextjs-

      - name: Build docs
        run: |
          bun --cwd docs build
          touch docs/out/.nojekyll