name: Issue Validator and Labeler

on:
  issues:
    types: [opened, edited]

jobs:
  validate-and-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate Issue Template and Add Labels
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require('./.github/scripts/validate.js')
            await script({github, context})